teuthology: refactored jenkins/util
switch deepsea-pr.sh to use common/util and common/teuthology
instead of jenkins/util

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

diff --git a/common/teuthology b/common/teuthology
--- a/common/teuthology
+++ b/common/teuthology
@@ -10,10 +10,26 @@ function extract_stack_trace() {
     # | head -n -1
 }
 
+function make_brief_deepsea_report() {
+    local teuthology_log=$1
+#grep -E "(Running task|Unwinding|Running DeepSea Stage|ERROR:teuthology|Stage.*(completed|failed))"
+    grep -s -q "Running task deepsea..." $teuthology_log || {
+        echo "The deepsea task hasn't been running. Probably teuthology issue"
+        return
+    }
+    grep -s -q "Running DeepSea Stage" $teuthology_log || {
+        echo "No DeepSea Stages ran. Looks like salt cluster deployment issue"
+        return
+    }
+    grep -E "(orchestration.*(completed|failed))" $teuthology_log | sed -E "s/.*\*+ ([^\*]*) \*+.*/\1/g"
+    return
+}
+
 function teuth_job_duration() {
     local $summary_yaml=$1
     printf "%.*f" 1 $(cat $summary_yaml | yj | jq -r .duration || echo "0")
 }
+
 function teuth_job_description() {
     local $info_yaml=$1
     cat $info_yaml | yj | jq -r .description
